### ISSUE TITLE
互动百科，是你在维护吗？

### ISSUE THREAD

**Issue by xiongxin** [zjhxmjl/hdwiki#1]
互动百科，是你在维护吗？官网的好像不更新了

**Comment by zjhxmjl** [comment]
目前是本人在维护

**Comment by fengkonghui** [comment]
怎么联系你？我公司有项目想用HDwiki，希望邀请你帮忙，加我的群110367113

**Comment by fengkonghui** [comment]
加我个人qq 1424335083 ？

**Comment by zjhxmjl** [comment]
抱歉回复晚了，不知你具体需要哪些支持？

**Comment by fengkonghui** [comment]
您好，
   我是红途公司的技术负责人，我们正在做针对金融行业人员的一款风控技术百科。目前，这个平台正在架构阶段，我的苦恼是不清楚hdwiki能否支持这样一个百科结构。
   我希望能和您保持联系，如有问题可请您技术指导下，我们愿意付费向您咨询。
   我的联系方式13066610639 qq 1424335083

**Comment by zjhxmjl** [comment]
本人一直在出差，可能空闲的时间较少，如果能帮得到你，可以免费提供技术支持

On November 18, 2014 9:41:00 AM GMT+08:00, "风控汇" notifications@github.com wrote:

> 您好，
> 我是红途公司的技术负责人，我们正在做针对金融行业人员的一款风控技术百科。目前，这个平台正在架构阶段，我的苦恼是不清楚hdwiki能否支持这样一个百科结构。
>   我希望能和您保持联系，如有问题可请您技术指导下，我们愿意付费向您咨询。
>   我的联系方式13066610639 qq 1424335083
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zjhxmjl/hdwiki/issues/1#issuecomment-63409324

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
