### ISSUE TITLE
创建词条的时候一直提示，词条标题含有危险代码,过滤后标题为空

### ISSUE THREAD

**Issue by Johnhacker** [zjhxmjl/hdwiki#2]
词条标题含有危险代码,过滤后标题为空
这是什么原因

**Comment by zjhxmjl** [comment]
@Johnhacker Hi,friend!你用的是从哪里下载的hdwiki源代码?
请检查lib/string.class.php下的substring function

**Comment by Johnhacker** [comment]
就是在git上下载的，我看可能这个version比较新，官网的是2014年的 ，经测试，此版本有点问题，但是官网那个没这个问题

**Comment by zjhxmjl** [comment]
@Johnhacker  重新下载最新的master分支再次安装

**Comment by Johnhacker** [comment]
@zjhxmjl 好的，另外想问下，有没有比较现代化的模板主题  ？谢谢
